final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_project/inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.index, name="index"),

    path('product/<product_id>', views.update_product, name='update_product'),
    path('customer/<customer_id>', views.update_customer, name='update_customer'),
    path('purchase/<purchase_id>', views.update_purchase, name='update_purchase'),
    path('stock/<stock_id>', views.update_stock, name='update_stock'),

    path('add-product', views.create_product, name='create_product'),
    path('add-customer', views.create_customer, name='create_customer'),
    path('add-purchase', views.create_purchase, name='create_purchase'),
    path('add-stock', views.create_stock, name='create_stock'),

    path('all-products', views.products, name='products'),
    path('all-customers', views.customers, name='customers'),
    path('all-stocks', views.stocks, name='stocks'),
    path('all-purchases', views.purchases, name='purchases'),

    path('del-product/<id>', views.delete_product, name='delete_product'),
    path('del-customer/<id>', views.delete_customer, name='delete_customer'),
    path('del-stock/<id>', views.delete_stock, name='delete_stock'),

    path('invoice/<purchase_id>', views.invoice, name='invoice'),

    path('fetch_price/<product_id>', views.fetch_price, name='fetch_price'),
]

final_project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.signin, name='login'),
    path('logout', views.signout, name='logout'),
    path('register', views.register, name='register'),

    path('all-users', views.users, name='users'),
]

final_project/inventory/models.py
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.
class Customer(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{8,15}$")
    phone = models.CharField(validators=[phoneNumberRegex], max_length=16, unique=True)

    def __str__(self):
        return f'{self.firstname} {self.lastname}, ({self.phone})'

class Product(models.Model):
    name = models.CharField(max_length=55)
    price = models.FloatField()
    image = models.ImageField(null=True, default='default.jpg')

    # property to return stock levels (all in - all out) (derived attr)
    @property
    def qty_in_stock(self):
        self.pk # use this as the id
        row = Stock.objects.filter(product_id=self.pk).all()
        qty_in = [obj.qty_in for obj in row]
        qty_out = [obj.qty_out for obj in row] 
        return sum(qty_in)-sum(qty_out)

    def __str__(self):
        return f'{self.name}'

class Purchase(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='purchases')
    date = models.DateTimeField(auto_now_add=True, blank=True)
    discount = models.FloatField(blank=True, null=True)
    product_list = models.ManyToManyField(Product, through='products_purchase', blank=True)

    # attribute to return sum of qty for all items in purchase
    @property
    def total_qty(self):
        items = products_purchase.objects.filter(purchase=self).all()
        qty = [item.qty for item in items]
        return sum(qty)

    # attribute to return sum of price for all items in purchase
    @property
    def total_price(self):
        items = products_purchase.objects.filter(purchase=self).all()
        amount = [item.amount for item in items]
        return sum(amount)

    def __str__(self):
        return f'{self.pk}) {self.customer} ({self.date})'


class products_purchase(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='sales')
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE, related_name='products')
    qty = models.IntegerField(default=1)
    selling_price = models.FloatField()

    @property
    def unit_price(self):
        return self.product.price

    @property
    def amount(self):
        return (self.unit_price*self.qty)
    
    # class for specifying row unique values (prevents duplicates)
    class Meta:
        unique_together = [['product','purchase']]

    def __str__(self):
        return f'{self.pk}) {self.product}, {self.purchase}'

class Stock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='inventory')
    qty_in = models.IntegerField(blank=True, default=0)
    qty_out = models.IntegerField(blank=True, default=0)
    description = models.CharField(max_length=100)
    products_purchase = models.OneToOneField(products_purchase,blank=True, null=True, on_delete=models.CASCADE, related_name='stockout')
    date = models.DateTimeField(auto_now_add=True, blank=True)
    price = models.FloatField(blank=True)

    def __str__(self):
        return f'{self.pk}) {self.product}, {self.qty_in}, {self.qty_out}, {self.description}, {self.date}'

final_project/inventory/forms.py
from django import forms

from .models import Product, Purchase, Customer, Stock, products_purchase


form_class = 'form-control'
form_style = 'max-width:50%;'

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={'class': form_class, 'style': form_style}),
            'price': forms.NumberInput(attrs={'class': form_class, 'style': form_style}),
        }

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ['customer','discount'] 
        widgets = {
            'customer' : forms.TextInput(attrs={'class': form_class, 'style': form_style}),
             'discount': forms.NumberInput(attrs={'class': form_class, 'style': form_style}),
        }   

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"
        widgets = {
            'firstname': forms.TextInput(attrs={'class': form_class, 'style': form_style}),
            'lastname': forms.TextInput(attrs={'class': form_class, 'style': form_style}),
            'phone' : forms.TextInput(attrs={'class': form_class, 'style': form_style})
        }
        
class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['product','qty_in','description','price']
        widgets = {
            'product' : forms.Select(attrs={'class': form_class, 'style': form_style}),
            'qty_in' : forms.NumberInput(attrs={'class': form_class, 'style': form_style}),
            'description': forms.TextInput(attrs={'class': form_class, 'style': form_style}),
            'price' : forms.NumberInput(attrs={'class': form_class, 'style': form_style})
        }        

class Products_PurchaseForm(forms.ModelForm):
    class Meta:
        model = products_purchase
        fields = '__all__'

final_project/inventory/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.models import Group, Permission

from .models import Product, Customer, Purchase, Stock, products_purchase
from .forms import ProductForm, PurchaseForm, CustomerForm, StockForm, Products_PurchaseForm

from datetime import datetime
import re

# Create your views here.
@login_required()
def index(request):
  
    return render(request, 'inventory/index.html', {
        'products': Product.objects.all(), 'customers': Customer.objects.all(),
        'purchases': Purchase.objects.all(), 'stocks': Stock.objects.all(),
    })

# READ
@login_required()
def products(request):
    return render(request, 'inventory/products.html', {'products': Product.objects.all()})

@login_required()
def customers(request):
    return render(request, 'inventory/customers.html', {'customers': Customer.objects.all()})

@login_required()
def stocks(request):
    return render(request, 'inventory/stocks.html', {'stocks': Stock.objects.all()})

@login_required()
def purchases(request):
    return render(request, 'inventory/purchases.html', {'purchases': Purchase.objects.all()})  

# UPDATE
@login_required()
def update_product(request,product_id):
    product = Product.objects.get(pk=product_id)
    form = ProductForm(instance=product)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('inventory:index'))
    
    context = {'product': product, 'form': form}
    return render(request, 'inventory/view_product.html', context)

@login_required()
def update_customer(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    form = CustomerForm(instance=customer)
    if request.method == 'POST':
        customer.firstname = request.POST.get('firstname')
        customer.lastname = request.POST.get('lastname')
        customer.save()
        return HttpResponseRedirect(reverse('inventory:index'))

    context = {'customer': customer, 'form':form}
    return render(request, 'inventory/view_customer.html', context)

@login_required()
def update_purchase(request, purchase_id):
    items = products_purchase.objects.filter(purchase=purchase_id).all()
    
    context = {'items': items, 'purchase': purchase_id, 'customers': Customer.objects.all(),}
    return render(request, 'inventory/view_purchase.html', context)

@login_required()
def update_stock(request, stock_id):
    stock = Stock.objects.get(pk=stock_id)
    form = StockForm(instance=stock)

    context = {'stock': stock, 'form':form}
    return render(request, 'inventory/view_stock.html', context)

# CREATE
@login_required()
def create_product(request):
    form =ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('inventory:products'))
        
    context = {'form':form}
    return render(request, 'inventory/add.html', context)

@login_required()
def create_customer(request):
    form = CustomerForm()
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('inventory:customers'))

    context = {'form':form}
    return render(request, 'inventory/add.html', context)

@login_required()
def create_purchase(request):
    if request.method == 'POST':
        customer = Customer.objects.get(pk=request.POST.get('customer'))
        products = request.POST.getlist('product')
        qtys = request.POST.getlist('qty')
        purchase = Purchase()
        purchase.customer = customer
        purchase.save()

        for idx in range(0,len(products)):
            product = Product.objects.get(pk=products[idx])
            
            purchase_item = products_purchase()
            purchase_item.purchase = purchase
            purchase_item.product = product
            purchase_item.qty = qtys[idx]
            purchase_item.selling_price = product.price
            purchase_item.save()

            stock = Stock()
            stock.product = product
            stock.qty_out = qtys[idx]
            stock.description = 'sale'
            stock.products_purchase = purchase_item
            stock.price = product.price
            stock.save()

        return HttpResponseRedirect(reverse('inventory:purchases'))

    context = {'customers': Customer.objects.all(), 'now': datetime.now(),
                'products': Product.objects.all(), 
    }
    return render(request, 'inventory/add_purchase.html', context)

@login_required()
def create_stock(request):
    form = StockForm()
    if request.method == 'POST':
        form = StockForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('inventory:stocks'))

    context = {'form':form}
    return render(request, 'inventory/add.html', context)

# DELETE
@login_required()
def delete_product(request, id):
    product = Product.objects.get(pk=id)
    product.delete()

    return HttpResponseRedirect(reverse('inventory:products'))

@login_required()
def delete_customer(request, id):
    customer = Customer.objects.get(pk=id)
    customer.delete()

    return HttpResponseRedirect(reverse('inventory:customers'))

@login_required()
def delete_stock(request, id):   
    stock = Stock.objects.get(pk=id)
    if stock.products_purchase == None:
        stock.delete()
    
    return HttpResponseRedirect(reverse('inventory:stocks'))

@login_required()
def invoice(request, purchase_id):
    items = products_purchase.objects.filter(purchase=purchase_id).all()

    context = {'items' : items, 'purchase_id': purchase_id}
    return render(request, 'inventory/invoice.html', context)

# PRICE FETCHER
def fetch_price(request, product_id):
    product = Product.objects.get(pk=product_id)
    if product:
        return HttpResponse(product.price)
    else:
        raise Http404('Cannot find price!!') 

final_project/inventory/templates/inventory/add.html
{% extends "layout.html" %}

{% block title %} Add- {% endblock %}

{% block body %}

<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            
            {{form.as_p}}
        
        </div>

        <div class="form-group">
            <input class="btn btn-success" type="submit">
        </div>
            
    </form>
</div>
      

{% endblock %}

final_project/inventory/templates/inventory/add_purchase.html
{% extends "layout.html" %}

{% block title %} Add-Purchase {% endblock %}

{% block script %}
<script>
    function showPrice(productId,priceId) {

        fetch(`fetch_price/${productId}`)
        .then(response => response.text())
        .then(data => {
            document.querySelector(`#price${priceId}`).value = data;
        })
    }
    // event handler for html element select of products
    function show (val) {
        let priceId = val.slice(-1);
        console.log(priceId);
        console.log(val);

        let product = document.querySelector(`#${val}`);
        showPrice(product.value,priceId);
        
     }
    
</script>
    
{%endblock%}

{% block body %}
<div class="container">
    <form method="POST" id="purchase-form">
        {% csrf_token %}
        <div class="d-flex flex-column align-items-center">
            <div class="form-group w-25">
                <label> Customer:</label>
                <select class="form-control" name="customer">
                    <option value="">------</option>
                    {% for customer in customers %}
                        <option value="{{customer.id}}">{{customer}}</option>
                    {% endfor %}
                </select>
            </div>
    
            <div class="form-group w-25">
                <label> Discount:</label>
                <input class="form-control" type="number" name="discount">
            </div>
    
            <div class="form-group w-25">
                <label> Date:</label>
                <input class="form-control" type="datetime" name="date" value="{{now}}" disabled>
            </div>
        </div>
        
        <div class="d-flex justify-content-between border rounded p-3" id="purchase-items0">
            <div class="form-group w-25">
                <label>Product:</label>
                <select class="form-control" onchange="show(this.id)" name="product" id="product-selection0">
                    <option value="">------</option>
                    {% for product in products %}
                        <option value="{{product.id}}">{{product.name}}</option>
                    {% endfor %}
                </select>
            </div>
            
            <div class="form-group w-25">
                <label>Qty:</label>
                <input class="form-control" type="number" name="qty" id="quantity">
            </div>
    
            <div class="form-group w-25">
                <label>Price:</label>
                <input class="form-control" type="number" id="price0" placeholder="price" disabled>
            </div>
            <button class="btn-sm btn-success my-4" id="add-clone0">Add</button>
        </div>
        
        <div class="form-group w-25 mt-3">
            <input class="btn btn-success" type="submit">
        </div>
        
    </form>

</div>
   
{% endblock %}

final_project/inventory/templates/inventory/customers.html
{% extends 'layout.html' %}

{% block title %} Customers {% endblock %}

{% block body %}

<!-- Dynamic Table with Export Buttons -->
<div class="block block-rounded">
    <div class="block-header">
        <button class="btn btn-outline-success mr-1 mb-3">
            <i class="fa fa-fw fa-plus mr-1"></i>
            <a href="{% url 'inventory:create_customer' %}">New Customer</a>
        </button>
    </div>
    <div class="block-content block-content-full">
        <!-- DataTables init on table by adding .js-dataTable-buttons class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _js/pages/be_tables_datatables.js -->
        <table class="table table-bordered table-striped table-vcenter js-dataTable-buttons">
            <thead>
                <tr>
                    <th class="text-center" style="width: 80px;">#</th>
                    <th>First Name</th>
                    <th class="d-none d-sm-table-cell" style="width: 30%;">Last Name</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Phone</th>
                    <th style="width: 15%;">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for customer in customers %}
                    <tr>
                        <td class="text-center font-size-sm">{{forloop.counter}}</td>
                        <td class="font-w600 font-size-sm">
                            <a href="#">{{customer.firstname}}</a>
                        </td>
                        <td class="d-none d-sm-table-cell font-size-sm">
                            <em class="text-muted">{{customer.lastname}}</em>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <span class="badge badge-success">{{customer.phone}}</span>
                        </td>
                        
                        <td class="text-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-alt-primary" href="{% url 'inventory:update_customer' customer.id %}">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                                <a class="btn btn-sm btn-alt-primary" href="{% url 'inventory:delete_customer' customer.id %}">
                                    <i class="fa fa-fw fa-times"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %} 
            </tbody>
        </table>
    </div>
</div>
<!-- END Dynamic Table with Export Buttons -->
{% endblock %}

final_project/inventory/templates/inventory/delete.html
{% extends "layout.html" %}

{% block title %} Delete- {% endblock %}

{% block body %}
    <form method="POST">
        {% csrf_token %}

        {{form.as_p}}
        
        <input type="submit">
    </form>

{% endblock %}

final_project/inventory/templates/inventory/index.html
{% extends 'layout.html' %}

{% block title %} Home {% endblock %}

{% block header %} Home {% endblock %}

{% block body %}
 
    

{% endblock %}

final_project/inventory/templates/inventory/products.html
{% extends 'layout.html' %}

{% block title %} Home {% endblock %}

{% block body %}

<!-- Dynamic Table with Export Buttons -->
<div class="block block-rounded">
    <div class="block-header">
        <button class="btn btn-outline-success mr-1 mb-3">
            <i class="fa fa-fw fa-plus mr-1"></i>
            <a href="{% url 'inventory:create_product' %}">New Product</a>
        </button>
    </div>
    <div class="block-content block-content-full">
        <!-- DataTables init on table by adding .js-dataTable-buttons class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _js/pages/be_tables_datatables.js -->
        <table class="table table-bordered table-striped table-vcenter js-dataTable-buttons">
            <thead>
                <tr>
                    <th class="text-center" style="width: 80px;">#</th>
                    <th>Name</th>
                    <th class="d-none d-sm-table-cell" style="width: 30%;">Price</th>
                    <th class="d-none d-sm-table-cell" style="width: 30%;">In Stock</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Actions</th>

                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td class="text-center font-size-sm">{{forloop.counter}}</td>
                        <td class="font-w600 font-size-sm">
                            <a href="#">{{product.name}}</a>
                        </td>
                        <td class="d-none d-sm-table-cell font-size-sm">
                            <em class="text-muted">{{product.price}}</em>
                        </td>
                        <td class="d-none d-sm-table-cell font-size-sm">
                            <em class="text-muted">{{product.qty_in_stock}}</em>
                        </td>
                        
                        <td class="text-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-alt-primary" href="{% url 'inventory:update_product' product.id %}">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                                <a class="btn btn-sm btn-alt-primary" href="{% url 'inventory:delete_product' product.id %}">
                                    <i class="fa fa-fw fa-times"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!-- END Dynamic Table with Export Buttons -->
{% endblock %}

final_project/inventory/templates/inventory/purchases.html
{% extends 'layout.html' %}

{% block title %} Purchases {% endblock %}

{% block body %}

<!-- Dynamic Table with Export Buttons -->
<div class="block block-rounded">
    <div class="block-header">
        <button class="btn btn-outline-success mr-1 mb-3">
            <i class="fa fa-fw fa-plus mr-1"></i>
            <a href="{% url 'inventory:create_purchase' %}">New Purchase</a>
        </button>    
    </div>
    <div class="block-content block-content-full">
        <!-- DataTables init on table by adding .js-dataTable-buttons class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _js/pages/be_tables_datatables.js -->
        <table class="table table-bordered table-striped table-vcenter js-dataTable-buttons">
            <thead>
                <tr>
                    <th class="text-center" style="width: 80px;">#</th>
                    <th>Customer Name</th>
                    <th class="d-none d-sm-table-cell" style="width: 30%;">Date</th>
                    <th class="d-none d-sm-table-cell" style="width: 10%;">Discount</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Total Items</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Total Price</th>
                    <th style="width: 10%;">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for purchase in purchases%}
                    <tr>
                        <td class="text-center font-size-sm">{{forloop.counter}}</td>
                        <td class="font-w600 font-size-sm">
                            <a href="#">{{purchase.customer.firstname}}</a>
                        </td>
                        <td class="d-none d-sm-table-cell font-size-sm">
                            <em class="text-muted">{{purchase.date}}</em>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            {{purchase.discount}}
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <span class="badge badge-success">{{purchase.total_qty}}</span>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            {{purchase.total_price}}
                        </td>
                        
                        <td class="text-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-alt-primary " href="{% url 'inventory:update_purchase' purchase.id %}">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                                <a class="btn btn-sm btn-alt-primary " href="#">
                                    <i class="fa fa-fw fa-times"></i>
                                </a>
                                <a class="btn btn-sm btn-alt-primary " href="{% url 'inventory:invoice' purchase.id %}">
                                    <i class="fa fa-fw fa-print"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %} 
            </tbody>
        </table>
    </div>
</div>
<!-- END Dynamic Table with Export Buttons -->
{% endblock %}

final_project/inventory/templates/inventory/stocks.html
{% extends 'layout.html' %}

{% block title %} Stocks {% endblock %}

{% block body %}

<!-- Dynamic Table with Export Buttons -->
<div class="block block-rounded">
    <div class="block-header">
        <button class="btn btn-outline-success mr-1 mb-3">
            <i class="fa fa-fw fa-plus mr-1"></i>
            <a href="{% url 'inventory:create_stock' %}">New Stock</a>
        </button>
    </div>
    <div class="block-content block-content-full">
        <!-- DataTables init on table by adding .js-dataTable-buttons class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _js/pages/be_tables_datatables.js -->
        <table class="table table-bordered table-striped table-vcenter js-dataTable-buttons">
            <thead>
                <tr>
                    <th class="text-center" style="width: 80px;">#</th>
                    <th>Product</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Qty In</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Qty Out</th>
                    <th class="d-none d-sm-table-cell" style="width: 30%;">Description</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Date</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Price</th>
                    <th style="width: 15%;">Actions</th>
                
                </tr>
            </thead>
            <tbody>
                {% for stock in stocks %}
                    <tr>
                        <td class="text-center font-size-sm">{{forloop.counter}}</td>
                        <td class="font-w600 font-size-sm">
                            <a href="#">{{stock.product.name}}</a>
                        </td>
                        <td class="d-none d-sm-table-cell font-size-sm">
                            <em class="text-muted">{{stock.qty_in}}</em>
                        </td>
                        <td class="d-none d-sm-table-cell font-size-sm">
                            <em class="text-muted">{{stock.qty_out}}</em>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            {{stock.description}}
                        </td>
                        <td class="d-none d-sm-table-cell">
                            {{stock.date}}
                        </td>
                        <td class="d-none d-sm-table-cell">
                            {{stock.price}}
                        </td>
                        
                        <td class="text-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-alt-primary" href="{% url 'inventory:update_stock' stock.id %}">
                                    <i class="fa fa-fw fa-pencil-alt"></i>
                                </a>
                                <a class="btn btn-sm btn-alt-primary" href="{% url 'inventory:delete_stock' stock.id %}">
                                    <i class="fa fa-fw fa-times"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% endfor %} 
            </tbody>
        </table>
    </div>
</div>
<!-- END Dynamic Table with Export Buttons -->
{% endblock %}

final_project/inventory/templates/inventory/view_customer.html
{% extends 'layout.html' %}

{% block title %} customer {% endblock %}

{% block body %}
<div class="container">
  <form action="" method="POST" >
    {% csrf_token %}
  
    {{form}}
    
    <input class="btn btn-success" type="submit" value="Save Changes">  
  </form>
     

  <a href="{% url 'inventory:customers' %}">back to all customers</a>
</div>
 
{% endblock %}

final_project/inventory/templates/inventory/view_product.html
{% extends 'layout.html' %}

{% block title %} products {% endblock %}

{% block body %}
<div class="container">
  <form action="" method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    
    {{form}}
  
    <div class="form-group">
      <input class="btn btn-success" type="submit" value="Save Changes">
    </div>
    
  </form>

    <img src="{{form.instance.image.url}}" style="max-width:200px; max-height:300px" class="float-right">
     
  <a href="{% url 'inventory:products' %}">back to all products</a>
</div>
 
{% endblock %}

final_project/inventory/templates/inventory/view_stock.html
{% extends 'layout.html' %}

{% block title %} stock {% endblock %}

{% block body %}

<div class="container">
  <form action="" method="POST" >
    {% csrf_token %}

    {{form}}
    
    <div class="form-group form-row">
      <input class="btn btn-success"type="submit" value="Save Changes">
    </div>

  </form>  

  <a href="{% url 'inventory:stocks' %}">back to all stocks</a>
</div>
  
{% endblock %}