final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_project/inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.index, name="index"),

    path('product/<product_id>', views.update_product, name='update_product'),
    path('customer/<customer_id>', views.update_customer, name='update_customer'),
    path('purchase/<purchase_id>', views.update_purchase, name='update_purchase'),
    path('stock/<stock_id>', views.update_stock, name='update_stock'),

    path('add-product', views.create_product, name='create_product'),
    path('add-customer', views.create_customer, name='create_customer'),
    path('add-purchase', views.create_purchase, name='create_purchase'),
    path('add-stock', views.create_stock, name='create_stock'),

    path('all-products', views.products, name='products'),
    path('all-customers', views.customers, name='customers'),
    path('all-stocks', views.stocks, name='stocks'),
    path('all-purchases', views.purchases, name='purchases'),

    path('del-product/<id>', views.delete_product, name='delete_product'),
    path('del-customer/<id>', views.delete_customer, name='delete_customer'),
    path('del-stock/<id>', views.delete_stock, name='delete_stock'),

    path('invoice/<purchase_id>', views.invoice, name='invoice'),

    path('fetch_price/<product_id>', views.fetch_price, name='fetch_price'),
]

final_project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.signin, name='login'),
    path('logout', views.signout, name='logout'),
    path('register', views.register, name='register'),

    path('all-users', views.users, name='users'),
]

final_project/templates/hero.html
{% load static %}

{% if 'login' in request.path %}

{% else %}
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                {% block header %} {% endblock %}
                {% if request.build_absolute_uri == "http://127.0.0.1:8000/inventory/" %}
                <small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted">
                    <a href="http://127.0.0.1:8000/admin/">To Admin Panel</a>
                </small>
                {% endif %}
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="{{ request.headers.referer }}">
                            {{request.headers.referer | cut:'http://127.0.0.1:8000/inventory/'}}
                        </a>
                    </li>
                    <li class="breadcrumb-item" aria-current="page">
                        {{request.build_absolute_uri | cut:'http://127.0.0.1:8000/inventory/'}}
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->

{% endif %}

final_project/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Icons -->
    <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
    <link rel="shortcut icon" href="{% static '/assets/media/favicons/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static '/assets/media/favicons/favicon-192x192.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/assets/media/favicons/apple-touch-icon-180x180.png' %}">
    <!-- END Icons -->

    <!-- Stylesheets -->
    <!-- Page JS Plugins CSS -->
    <link rel="stylesheet" href="{% static '/assets/js/plugins/datatables/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static '/assets/js/plugins/datatables/buttons-bs4/buttons.bootstrap4.min.css' %}">
    
    <!-- Fonts and OneUI framework -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap">
    <link rel="stylesheet" id="css-main" href="{% static '/assets/css/oneui.min.css' %}">

    <!-- You can include a specific file from css/themes/ folder to alter the default color theme of the template. eg: -->
    <!-- <link rel="stylesheet" id="css-theme" href="{% static '/assets/css/themes/amethyst.min.css' %}"> -->
    <!-- END Stylesheets --> 

    <link rel="stylesheet" href="{% static 'inventory/style.css' %}">
     
    <title>
        {% block title %} Document {% endblock %}
    </title> 
</head>
<body>
    {% include 'navbar.html' %}
    
    {% include 'hero.html' %}
    
    {% block body %}
    
    {% endblock %}
    
    <!-- Custom Js file -->
    <script src="{% static 'inventory/js/app.js' %}"></script>
    {% block script %} {% endblock %}
    <!--
        OneUI JS Core
        
        Vital libraries and plugins used in all pages. You can choose to not include this file if you would like
        to handle those dependencies through webpack. Please check out assets/_js/main/bootstrap.js for more info.
        
            If you like, you could also include them separately directly from the assets/js/core folder in the following
            order. That can come in handy if you would like to include a few of them (eg jQuery) from a CDN.

            assets/js/core/jquery.min.js
            assets/js/core/bootstrap.bundle.min.js
            assets/js/core/simplebar.min.js
            assets/js/core/jquery-scrollLock.min.js
            assets/js/core/jquery.appear.min.js
            assets/js/core/js.cookie.min.js
        -->
        <script src="{% static '/assets/js/oneui.core.min.js' %}"></script>

        <!--
            OneUI JS

            Custom functionality including Blocks/Layout API as well as other vital and optional helpers
            webpack is putting everything together at assets/_js/main/app.js
        -->
        <script src="{% static '/assets/js/oneui.app.min.js' %}"></script>

        <!-- Page(s) JS Plugins -->
        <script src="{% static '/assets/js/plugins/datatables/jquery.dataTables.min.js' %}"></script>
        <script src="{% static '/assets/js/plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>
        <script src="{% static '/assets/js/plugins/datatables/buttons/dataTables.buttons.min.js' %}"></script>
        <script src="{% static '/assets/js/plugins/datatables/buttons/buttons.print.min.js' %}"></script>
        <script src="{% static '/assets/js/plugins/datatables/buttons/buttons.html5.min.js' %}"></script>
        <script src="{% static '/assets/js/plugins/datatables/buttons/buttons.flash.min.js' %}"></script>
        <script src="{% static '/assets/js/plugins/datatables/buttons/buttons.colVis.min.js' %}"></script>
        <script src="{% static '/assets/js/plugins/jquery-validation/jquery.validate.min.js' %}"></script>

        <!-- Page(s) JS Code -->
        <script src="{% static '/assets/js/pages/be_tables_datatables.min.js' %}"></script>
        <script src="{% static '/assets/js/pages/op_auth_signin.min.js' %}"></script>
</body>
</html>

final_project/templates/navbar.html
{% load static %}

{% if 'login' in request.path %}

{% else %}
<div class="bg-white p-3 push">
     <!-- Toggle Navigation -->
     <div class="d-lg-none">
        <!-- Class Toggle, functionality initialized in Helpers.coreToggleClass() -->
        <button type="button" class="btn btn-block btn-light d-flex justify-content-between align-items-center" data-toggle="class-toggle" data-target="#horizontal-navigation-click-justified" data-class="d-none">
            Menu - Click Justified
            <i class="fa fa-bars"></i>
        </button>
    </div>
    <!-- END Toggle Navigation -->

    <!-- Navigation -->
    <div id="horizontal-navigation-click-justified" class="d-none d-lg-block mt-2 mt-lg-0">
        <ul class="nav-main nav-main-horizontal nav-main-horizontal-justify">
            <!-- home -->
            <li class="nav-main-item">
                <a class="nav-main-link" href="{% url 'inventory:index' %}">
                    <i class="nav-main-link-icon fa fa-home"></i>
                    <span class="nav-main-link-name">Home</span>
                </a>
            </li>
            <!-- products -->
            <li class="nav-main-item">
                <a class="nav-main-link" href="{% url 'inventory:products' %}">
                    <i class="nav-main-link-icon far fa-file-alt"></i>
                    <span class="nav-main-link-name">Products</span>
                </a>
            </li>
            <!-- customers -->
            <li class="nav-main-item">
                <a class="nav-main-link" href="{% url 'inventory:customers' %}">
                    <i class="nav-main-link-icon far fa-file-alt"></i>
                    <span class="nav-main-link-name">Customers</span>
                </a>
            </li>
            <!-- stocks -->
            <li class="nav-main-item">
                <a class="nav-main-link" href="{% url 'inventory:stocks' %}">
                    <i class="nav-main-link-icon far fa-file-alt"></i>
                    <span class="nav-main-link-name">Stocks</span>
                </a>
            </li>
            <!-- purchases -->
            <li class="nav-main-item">
                <a class="nav-main-link" href="{% url 'inventory:purchases' %}">
                    <i class="nav-main-link-icon far fa-file-alt"></i>
                    <span class="nav-main-link-name">Purchases</span>
                </a>
            </li>
            <!-- users -->
            <li class="nav-main-item">
                <a class="nav-main-link" href="{% url 'users:users' %}">
                    <i class="nav-main-link-icon far fa-file-alt"></i>
                    <span class="nav-main-link-name">Users</span>
                </a>
            </li>

            <!-- user panel -->
            <!-- <li class="nav-main-item"> -->
               <!-- User Dropdown -->
               <div class="dropdown d-inline-block ml-2">
                <button type="button" class="btn btn-sm btn-dual d-flex align-items-center" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle" src="{% static '/assets/media/avatars/avatar10.jpg' %}" alt="Header Avatar" style="width: 21px;">

                    <span class="d-none d-sm-inline-block ml-2">{{user.username}}</span>
                    <i class="fa fa-fw fa-angle-down d-none d-sm-inline-block ml-1 mt-1"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-md dropdown-menu-right p-0 border-0" aria-labelledby="page-header-user-dropdown">
                    <div class="p-3 text-center bg-primary-dark rounded-top">
                        <img class="img-avatar img-avatar48 img-avatar-thumb" src="{% static '/assets/media/avatars/avatar10.jpg' %}" alt="">
                        <p class="mt-2 mb-0 text-white font-w500">{{user.username}}</p>
                        <p class="mb-0 text-white-50 font-size-sm">Role</p> 
                    </div>
                    <div class="p-2">
                        
                        <div role="separator" class="dropdown-divider"></div>
                        <a class="dropdown-item d-flex align-items-center justify-content-between" href="#">
                            <span class="font-size-sm font-w500">Lock Account</span>
                        </a>
                        <a class="dropdown-item d-flex align-items-center justify-content-between" href="{% url 'users:logout' %}">
                            <span class="font-size-sm font-w500">Log Out</span>
                        </a>
                    </div>
                </div>
            </div>
            <!-- END User Dropdown -->
            <!-- </li> -->

        </ul>
    </div>
    <!-- END Navigation -->
</div>

{% endif %}